development:
  cloud_name: <%=Rails.application.credentials.cloud_name%>
  api_key: <%=Rails.application.credentials.api_key%>
  api_secret: <%=Rails.application.credentials.api_secret%>
  secure: true
  cdn_subdomain: true
